import { Raleway } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";

const raleway = Raleway({
  variable: "--font-outfit",
  subsets: ["latin"],
});

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Поиск врача в один клик",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <body className={raleway.className}>
        <div  className="md:px-20">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
